// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV5R984edQzdQkoeMRK1FkxpAfkj5Tjes',
    appId: '1:109228684267:web:3de0baa3781c15c8b4dfae',
    messagingSenderId: '109228684267',
    projectId: 'medihub-c5e58',
    authDomain: 'medihub-c5e58.firebaseapp.com',
    storageBucket: 'medihub-c5e58.firebasestorage.app',
    measurementId: 'G-6NNGGQ94S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5aW6Gn4dSKQb0QcttynhmvdmldSx_eF0',
    appId: '1:109228684267:android:802c3f1c2acc7fe4b4dfae',
    messagingSenderId: '109228684267',
    projectId: 'medihub-c5e58',
    storageBucket: 'medihub-c5e58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMLpYPRSL0WfAHkjm80ei33Degacnu7RM',
    appId: '1:109228684267:ios:5638315ae3699d47b4dfae',
    messagingSenderId: '109228684267',
    projectId: 'medihub-c5e58',
    storageBucket: 'medihub-c5e58.firebasestorage.app',
    iosClientId: '109228684267-hh00s2v5feeso07oon4sqabdcbmph5em.apps.googleusercontent.com',
    iosBundleId: 'com.example.medibd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMLpYPRSL0WfAHkjm80ei33Degacnu7RM',
    appId: '1:109228684267:ios:5638315ae3699d47b4dfae',
    messagingSenderId: '109228684267',
    projectId: 'medihub-c5e58',
    storageBucket: 'medihub-c5e58.firebasestorage.app',
    iosClientId: '109228684267-hh00s2v5feeso07oon4sqabdcbmph5em.apps.googleusercontent.com',
    iosBundleId: 'com.example.medibd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV5R984edQzdQkoeMRK1FkxpAfkj5Tjes',
    appId: '1:109228684267:web:43a7544fdb4c7897b4dfae',
    messagingSenderId: '109228684267',
    projectId: 'medihub-c5e58',
    authDomain: 'medihub-c5e58.firebaseapp.com',
    storageBucket: 'medihub-c5e58.firebasestorage.app',
    measurementId: 'G-WQ1R2PJJSJ',
  );
}
